---
- name: Ensure xcenv is installed
  homebrew:
    name: xcenv
    state: present

- name: 'Ensure {{ xcenv_root }} directory is created'
  file:
    path: '{{ xcenv_root }}'
    state: directory
    mode: 0755

- name: Ensure Homebrew installed tools are not shimmed
  shell: comm -12 <(ls /usr/local/bin) <(echo {{ xcenv_shim_tools | join(' ') }} | tr ' ' '\n')
  args:
    executable: /bin/zsh # default /bin/sh does not handle process substitution but zsh does
  register: homebrew_installed_tools

# Uncomment for troubleshooting
# - name: Print return information from the previous task
#   ansible.builtin.debug:
#     var: homebrew_installed_tools

# - name: Print templating results
#   ansible.builtin.debug:
#     msg: "{{ lookup('template', './xcenv.sh.j2') }}"

- name: Ensure xcenv is added to profile system-wide
  blockinfile:
    path: /etc/zprofile
    block: "{{ lookup('template', 'xcenv.sh.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK -- XCENV"
  become: yes

- name: 'Ensure Xcode {{ xcenv_default_xcode }} is default'
  shell: $SHELL -lc 'xcenv global {{ xcenv_default_xcode|quote }}'

- name: Ensure shims are updated
  shell: $SHELL -lc 'xcenv rehash'
